services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: oscar
      POSTGRES_PASSWORD: Hannah#0103
      POSTGRES_DB: bows
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
